export const metadata = {
  title: "Mock Test",
  description: "Generated by Satish Maurya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
