import Footer from "@/components/Footer";
import { SessionWrapper } from "@/components/SessionWrapper";
import "./globals.css"
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Mock Test",
  description: "Generated by Satish Maurya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SessionWrapper>
        <Navbar/>
        {children}
        <Footer/>
      </SessionWrapper>
      </body>
    </html>
  );
}
